### ISSUE TITLE
Security Issue: Hardcoded API key

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#10]
Hey not sure if you're aware of this but we can still see the API key even though you removed it. I highly recommend regenerating your key if possible for your own security

https://github.com/BestOfAllCoding/SUPLauncher-Reborn/commit/6b7a3753b0a155eabe839b734fc699bfd2219b6b#r80219716

**Comment by aidanH39** [comment]
It’s a old key. Will be useless now.
