### ISSUE TITLE
[BUG] Profile overlay moving does not point to cursor 

### ISSUE THREAD

**Issue by Schmitin** [BestOfAllCoding/SUPLauncher-Reborn#18]
**Describe the bug**
When moving the steam ID lookup in the staff overlay, the window does not align with the cursor.

**To Reproduce**
1. Go to 'Settings'
2. Enable Staff Overlay
3. Copy a Steam ID
4. Attempt to move the result window.

**Expected behavior**
The point clicked on the window, likely near the top, is where the window anchors to the cursor while it is being moved. Similar to any other window you'd expect to be able to move around.

**Screenshots**

https://user-images.githubusercontent.com/59183604/183229425-c118d9aa-905c-4efe-a5ff-3d12e8c707b4.mp4

**Additional context**
Another related bug: If you try to position the overlay at the top of your screen, it'll maximize and take up the whole screen like you'd expect something like a browser to do.

**Comment by aidanH39** [comment]
https://github.com/BestOfAllCoding/SUPLauncher-Reborn/commit/db9bf539473d684156c3236774a3e80db6fea868

**Comment by Schmitin** [comment]
Pog
