### ISSUE TITLE
Suggestion: Add winget implimentation

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#2]
Hey so I'm not sure if your familiar with the windows package manager called winget. But it might be a good idea to put this on there; it'll stop the windows smart-screen and virus popups making the software seem more safe. It will also allow for an easy 1 command install and auto updating etc. 

You can find winget here https://github.com/microsoft/winget-pkgs 

I personally recommend that you use GitHub actions to automatically upload new releases. There's one i use here. https://github.com/vedantmgoyal2009/winget-releaser

**Comment by aidanH39** [comment]
oh, this looks cool. I was looking for something like this. I'll check this out tomrrow morning.
