### ISSUE TITLE
[FEATURE REQUEST] Add marketplace catagorys

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#21]
**Suggestion Type:** Application suggestion

**Describe the solution you'd like**
Simple enough really just add some basic catagorys things along the lines of. Bases; rp bases; gambling machines; art etc etc etc
bet to add it now while the dupes are limited then later and just have a pile of misc dupes

**Comment by aidanH39** [comment]
I'll make a start on it now. Hopefully will be done today.

**Comment by zephiowl** [comment]
Sounds good!

**Comment by zephiowl** [comment]
@BestOfAllCoding Thought of a followup if possible make it so when the dupes download in the advanced dupe folder that it follows the catagorys too. So itd be like Advdupe > Market > RP > dupe.txt kinda thing

**Comment by aidanH39** [comment]
https://github.com/BestOfAllCoding/SUPLauncher-Reborn/commit/73549e1036f6fcebec50b8ae62371ee51250bf1d
