### ISSUE TITLE
More detail on the new dupe marketplace and the data involved

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#22]
Hey so I see the new dupe marketplace and just had a few questions more about behind the scenes as i don't see a wiki page on it

1. Where is the data held? Local ftp? online cloud storage if so what company etc
2. Is the data encrypted?
3. Could you provide more detail on HOW you use our data.
4. What exactly might be considered "inappropiate content" as mentioned in your terms

**Comment by aidanH39** [comment]
https://github.com/BestOfAllCoding/SUPLauncher-Reborn/wiki/Dupe-Marketplace

**Comment by zephiowl** [comment]
@BestOfAllCoding Love it but details on the storage itself has not been provided, Where is the information located? Locally; remote etc? Is it encrypted; on a local server? Cloud storage etc.

**Comment by aidanH39** [comment]
my bad, added it now

**Comment by zephiowl** [comment]
Thank you sir
