### ISSUE TITLE
[BUG] Package is not pushing to winget

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#26]
**Describe the bug**
Github is not pushing to winget

View https://github.com/BestOfAllCoding/SUPLauncher-Reborn/actions

**Expected behavior**
It should successfully push to winget

**Screenshots**
![image](https://user-images.githubusercontent.com/66909997/183247360-549f10f4-6c1b-4a02-bfa6-8f2756981549.png)

**Additional context**
Add any other context about the problem here. If you can add any error logs / Exception messages please do.
It appears your missing the WINGET_TOKEN that was mandatory i highly reccomend you doubble back on https://github.com/BestOfAllCoding/SUPLauncher-Reborn/pull/3 and ensure that you followed the steps correctly. If you have any issues contact me on discord <3

**Comment by aidanH39** [comment]
yeah, will need to go over this. added a token before. then it said something like. package version required or something along lines of that. will try and get this setup once i have time.

**Comment by zephiowl** [comment]
Sounds like a fun time; contact me on discord at any point if you have issues

**Comment by zephiowl** [comment]
@BestOfAllCoding I can see that even in your most recent release 2.3.1 winget still isn't being pushed too. Do you need any help I'd be more then happy to work with you if you do.
