### ISSUE TITLE
[BUG] Overlays persist after gmod closes.

### ISSUE THREAD

**Issue by Schmitin** [BestOfAllCoding/SUPLauncher-Reborn#30]
**Describe the bug**
Overlays persist after gmod closes.

**To Reproduce**
1. Enable Overlay
2. Use Overlay Ingame
3. Close Gmod
4. See Overlay on Desktop/Whatever was in the background.

**Expected behavior**
Overlay closes with the application.

**Comment by aidanH39** [comment]
Yeah. I forgot about this. I’ll sort it out next next update. Should close the overlay once tabbed out
