### ISSUE TITLE
[BUG] Default keybind settings won't save.

### ISSUE THREAD

**Issue by Schmitin** [BestOfAllCoding/SUPLauncher-Reborn#31]
**Describe the bug**
Default keybind settings won't save.

**To Reproduce**
1. Go to Settings
2. Change none of the keybinds, enable checkboxes.
3. Click save.

**Expected behavior**
Default settings should be able to be saved. They function by default in-game.

**Screenshots**
![BUG](https://user-images.githubusercontent.com/59183604/183268924-3c107d7c-5c9d-4ed6-8ccc-dd785b1991b0.png)

**Comment by aidanH39** [comment]
So basically what it checks for is already in use key binds. Since you have the default ones set it won’t allow you to chose them again. I can fix this next update.

The save settings button only actually saves the key binds. When you check the checkboxes they are automatically saved.
