### ISSUE TITLE
[BUG] First join time isn't functional

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#35]
**Describe the bug**
On the UI profile overlay the "first join" isn't accurate at all.

**To Reproduce**
1. Copy a SteamID
2. Turn on the SUP overlay
3. See error

**Expected behavior**
It should display the accurate first join date

**Screenshots**
![Garry's Mod Screenshot 2022 08 16 - 11 39 39 21](https://user-images.githubusercontent.com/66909997/184783681-2d2ae1bf-ba3c-4893-a6eb-ffe7e2e17032.png)

![image](https://user-images.githubusercontent.com/66909997/184783722-e58c3e1c-e702-4d32-aa0b-2a0632f3a7ca.png)

**Comment by aidanH39** [comment]
https://github.com/BestOfAllCoding/SUPLauncher-Reborn/commit/dea6580182dc403067a527b66902329160118980

Be fixed next update. When I release
