### ISSUE TITLE
[BUG] Minimizing launcher to system tray breaks the launcher.

### ISSUE THREAD

**Issue by Schmitin** [BestOfAllCoding/SUPLauncher-Reborn#39]
**Describe the bug**
After opening the launcher from being minimized in the system tray, the window will open with many of the assets missing and the launcher becomes unusable until fully closed and re-launched.

**To Reproduce**
1. Minimize the launcher to the system tray.
2. Click on the launcher in the system tray.
3. Witness the broken launcher.
4. Force close & restart.

**Expected behavior**
When re-opening the launcher from the system tray, it should remain functional for further use.

**Screenshots**
I will reply to this issue with a video.

**Comment by aidanH39** [comment]
Wont be present in V3.0.0+
