### ISSUE TITLE
Suggestion: Add a suggestion template

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#5]
Hey so i'm probably going to be submitting quite a few suggestions and recommend that you add a suggestions template or a discussion board.

Pretty self explanatory if you need any help just let me know and i'll help out

**Comment by aidanH39** [comment]
https://github.com/BestOfAllCoding/SUPLauncher-Reborn/commit/bd9c341d9822c88ebb28254d7018c725cc8a131f - Added
