### ISSUE TITLE
Suggestion: Add an income/expenses overlay

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#6]
Hey so a suggestion i have basically rip the idea of the casino owner for income and expenses. But have it carry across an entire play session instead; a possible method of doing this may simply be pulling the amount of money a user has every minute or so from the sup website; and comparing that against a variable that was assigned when they first opened the sup-launcher; or connected to a server trough it.

Not sure how possible this is as i don't have any experience with C# but i believe it would be a great idea until it eventually gets ported into the base server.

**Comment by aidanH39** [comment]
been added in the sup update. so no point for this really.
