### ISSUE TITLE
[FEATURE REQUEST] Add shareable dupes

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#7]
**Suggestion Type:** Application suggestion

**Describe the solution you'd like**
Hey so i was thinking that a possible improvement would be hooking your application into an ftp server or git-hub repo etc. And allowing users to both share; and download dupes from within the launcher itself. Possibly even having some dupes be encrypted so you'd have to "Buy" the decryption key essentially allowing users to "Sell" dupes in-game might be cool too!

**Comment by aidanH39** [comment]
Ok. This is a fking cool idea. The whole buying thing I’m not into that much. Stoned will probably have problems with that. But this is definitely a idea I’m into.

**Comment by zephiowl** [comment]
Well i mean people already buy and sell dupes all the time; i personally have brought like about 8k dupes. So not sure what he'd be upset about. But yeah just the overall idea would be great! Its something i think the community at large would benefit a lot from especially newer users! (Also i meant with in-game money not irl if that's what your thinking)

**Comment by aidanH39** [comment]
https://github.com/BestOfAllCoding/SUPLauncher-Reborn/commit/fa333301c78937140c74aac03a5dc385117e45c3
