### ISSUE TITLE
[FEATURE REQUEST] Staff easy alt check

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#8]
**Suggestion Type:** Application suggestion

**Is your feature request related to a problem? Please describe.**
Alt checks take alot of time and going trough the fourms is quite the bit of effort.

**Describe the solution you'd like**
Hook into [Steams familysharing API](https://api.steampowered.com/IPlayerService/IsPlayingSharedGame/v0001/?key=(DevKey)&steamid=(TargetSTEAMID64DEC)&appid_playing=(STEAMGAMEID)&format=json) to quickly and easily see if an account is using steams family sharing service. Its not a 100% fullproof system but its another tool that could substantially help out the staff team.

**Describe alternatives you've considered**
Continuing to use the current system

**Comment by aidanH39** [comment]
actually already on todo list. I would have to let people know that they cannot ban for this straight away. But it would still be useful yeh.

https://github.com/users/BestOfAllCoding/projects/2/views/1

**Comment by zephiowl** [comment]
> actually already on todo list. I would have to let people know that they cannot ban for this straight away. But it would still be useful yeh.
> 
> https://github.com/users/BestOfAllCoding/projects/2/views/1

Oh well damn i didn't see your project board; my apologies! Glad to know its a good idea though.

**Comment by aidanH39** [comment]
> > actually already on todo list. I would have to let people know that they cannot ban for this straight away. But it would still be useful yeh.
> > https://github.com/users/BestOfAllCoding/projects/2/views/1
> 
> Oh well damn i didn't see your project board; my apologies! Glad to know its a good idea though.

Only just put it public that’s why. :)

**Comment by aidanH39** [comment]
Was looking to add this in this update. but looks like the API endpoint doesn't work anymore. I could however check if the player actually owns the game, instead. But would not be much of a help.

**Comment by zephiowl** [comment]
I wounder why they removed that endpoint; it was something that tons of people used! And i mean you could do that as most people would still family share and if your on an account that doesn't own the game that means there's at least a possibility. I think that you should still add it but have a little bit of a warning or easy way for users to see that its not guaranteed.

@BestOfAllCoding
