### ISSUE TITLE
[FEATURE REQUEST] Autobackup Dupes

### ISSUE THREAD

**Issue by zephiowl** [BestOfAllCoding/SUPLauncher-Reborn#9]
**Suggestion Type:** Application suggestion

**Is your feature request related to a problem? Please describe.**
The amount of times that Me or my friends have had their dupes corrupt or accidentally deleted etc its horrible

**Describe the solution you'd like**
Hook into a users git hub account via a git hub token; then make new commits every time changes are detected in the dupe folder; it'll have automatic version history. And easy sharing with other users (if they set the repo to public)

**Describe alternatives you've considered**
Manually backing up your dupes everytime... But thats effort

**Comment by aidanH39** [comment]
I mean technically the dupe market place stores your dupes. It doesn’t automatically update them though. I mean if there’s any other people that want this I may add it.

but to me it sort of looks pointless.

**Comment by aidanH39** [comment]
Also https://forum.superiorservers.co/topic/41509-guide-automatically-store-dupes-on-the-cloud-windows/ very useful for keeping dupes on the cloud. Will be more reliable then storing them on my end.

**Comment by zephiowl** [comment]
@BestOfAllCoding Whenever you do something about a report if you could close it that would be great; either fixing a bug; deciding that you wont add a feature; or the commit in which you do add that feature etc. It just stops there being tons of open issues. 

I've closed this one because you stated it's pointless meaning it wont be added
